annisadeviPPW/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage1, name='profile'),
    path('profile2', views.homepage2, name='profile2'),
    path('hobby', views.hobby, name='hobby')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def homepage1(request):
    return render(request, 'main/homepage1.html')

def homepage2(request):
    return render(request, 'main/homepage2.html')

def hobby(request):
    return render(request, 'main/hobby.html')

main/templates/main/hobby.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    {% block style %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/homepage2.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% endblock style %}
    <title> SecondPage Kak PW </title>
</head>

<body>
    {% block content %}
    <section id="hobby">
       
        <div class="hobby col">
            <h4>HOBBY</h4>
            <h5>Cake Making Documentations</h5>
            <div class="kue1 row">
                <img id="kue" src="{% static 'main/image/Kue1.png' %}"/> 
                <img id="kue" src="{% static 'main/image/Kue2.png' %}"/> 
                <img id="kue" src="{% static 'main/image/Kue3.png' %}"/> 
                <img id="kue" src="{% static 'main/image/Kue4.png' %}"/> 
            </div>
            <div class="kue2 row">
                <img id="kue" src="{% static 'main/image/Kue5.png' %}"/> 
                <img id="kue" src="{% static 'main/image/Kue6.png' %}"/> 
                <img id="kue" src="{% static 'main/image/Kue7.png' %}"/> 
                <img id="kue" src="{% static 'main/image/Kue8.png' %}"/> 
            </div>
            <img id="asetoval4" src="{% static 'main/image/AsetOval4.png' %}"/>
            <img id="gelombang" src="{% static 'main/image/Gelombang2.png' %}" alt="asset">
        </div>
    </section>

    <section id="project">
        <div class="hobby col">
            <h4>PROJECT</h4>
            <div class="bool row">
                <img class="boolean" src="{% static 'main/image/bool1.png' %}" alt="Boolean">
                <img id="boolean2" src="{% static 'main/image/bool2.png' %}" alt="Boolean">
                <img class="boolean" src="{% static 'main/image/bool3.png' %}" alt="Boolean">
            </div>
            <a href="https://bit.ly/Boolean26Media2020"> 
                <img  id="booleanlink" src="{% static 'main/image/button2.png'%}" alt="Boolean26">
            </a> 
            <img id="asetoval3" src="{% static 'main/image/AsetOval3.png' %}" alt="asset">
        </div>
    </section>

    
    {% endblock content %}
</body>
</html>

main/templates/main/homepage1.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
    {% block style %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/homepage1.css' %}">
    {% endblock style %}
    <title> Hello World! </title>
</head>

<body>
    {% block content %}
    <div class="page1">
        <div class="tulisan">
            <h1> Hi! </h1>
            <h2> Annisa Devi Nurmalasari's here </h2> <br>
            <h3> | Fasilkom UI | </h3> <br>
        </div>
        <div class="foto">
            <img id="fotoku" src="{% static 'main/image/foto2.png' %}" alt="My Photo">
        </div>
    </div>
    <div class="page2">
        <div class="deskripsi">
            <h1 id="Aboutme"> Tentang Saya </h1>
            <p> Nama saya Annisa Devi Nurmalasari. Saya lahir tanggal 11 Desember 2000. Saya berasal dari Tangerang. Hobi saya ngidol. Saya sedang belajar PPW di Fasilkom. </p>
        </div>
        
        <div class="Datadiri">
            <div class="profile">
                <h1 id="judul"> Profile Saya </h1>
                <div class="profilekolommaster">
                    <div class="profilekolom1">
                        <h2 id="semijudul"> Nama </h2>
                        <h3 id="keterangan"> Annisa Devi Nurmalasari </h3>
                        <h2 id="semijudul"> NPM </h2>
                        <h3 id="keterangan"> 1906292894 </h3>
                        <h2 id="semijudul"> Angkatan </h2>
                        <h3 id="keterangan"> 2019 </h3>
                    </div>
                    <div class="profilekolom2">
                        <h2 id="semijudul"> Kuliah </h2>
                        <h3 id="keterangan"> Universitas Indonesia </h3>
                        <h2 id="semijudul"> Hobi </h2>
                        <h3 id="keterangan"> Youtube-an </h3>
                    </div>
                </div>
            </div>
            <div class="akademik">
                <h1 id="judul"> Akademik </h4>
                <table border="1">
                    <tr>
                        <td> Tahun </td>
                        <td> Nama Institusi </td>
                    </tr> 
                    <tr>
                        <td> 2006-2013 </td>
                        <td> SDN Sukasari 4 </td>
                    </tr>
                    <tr>
                        <td> 2013-2016 </td>
                        <td> SMPN 1 Kota Tangerang </td>
                    </tr>
                    <tr>
                        <td> 2016-2019 </td>
                        <td> SMAN 1 Kota Tangerang </td>
                    </tr>
                    <tr>
                        <td> 2019-Sekarang </td>
                        <td> Universitas Indonesia </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    
    {% endblock content %}
</body>

</html>

main/templates/main/homepage2.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}
    <link rel="stylesheet" href="{% static 'main/css/homepage2.css' %}">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% endblock style %}
    <title> Website Kak PW </title>
</head>

<body>
    {% block content %}
    <section id="homepage">
        <div class="homepage col">
            <div class="middle row">
                <div class="text col">
                    <h1>Hi!</h1>
                    <h2>Annisa Devi<br>Nurmalasari's here</h2>
                    <h3>|  Computer Science  |</h3>
                    <a href="#profile">
                        <img id="button" src="{% static 'main/image/AboutmeButton.png' %}" alt="Foto">
                    </a>
                </div>
                    <img id="fotobesar" src="{% static 'main/image/Foto3.png' %}" alt="Foto">
            </div>
            <img id="gelombang" src="{% static 'main/image/Gelombang1.png' %}" alt="asset">
    </section>
    <section id="profile">
        <div class="profile col">
            <h4>ABOUT ME</h4>
            <div class="kontenprofile row">
                <div class="deskripsi col">
                    <img id="fotokecil" src="{% static 'main/image/deskripsifoto.png' %}" alt="Foto">
                    <p>
                        Hello, my name is Annisa Devi Nurmalasari but you can call me Icha/Ichul. I’m 19 years old and<br>from Tangerang. Now, i’m a college student of Computer Science in Universitas Indonesia
                    </p>
                </div>
                <img id="rectangle1" src="{% static 'main/image/Rectangle1.png' %}">
                <div class="datadiri col">
                    <h5>Name</h5>
                    <h6>Annisa Devi Nurmalasari</h6>
                    <h5>Age</h5>
                    <h6>19</h6>
                    <h5>Date of Birth</h5>
                    <h6>Tangerang, December 11th 2000</h6>
                    <h5>Website</h5>
                    <h6>annisadevi.herokuapp.com</h6>
                    <h5>Contact</h5>
                    <h6>adevi.nurmalasari@gmail.com</h6>
                    <h5>Jobs</h5>
                    <h6>Student of Computer Science</h6>
                    <h5>Hobby</h5>
                    <h6>Youtube-ing, Idol-ing, Cake Making</h6>
                </div>
            </div>
            <img id="asetoval1" src="{% static 'main/image/AsetOval1.png' %}">
        </div>
    </section>
    <section id="academics">
        <div class="academics col">
            <h4>ACADEMICS</h4>
            <div class="kontenacademics row">
                <div class="education col">
                    <h4>Educational Level</h4>
                    <h5>SDN Sukasari 4</h5>
                    <h6>year 2006-2013</h6>
                    <h5>SMPN 1 Kota Tangerang</h5>
                    <h6>year 2013-2016</h6>
                    <h5>SMAN 1 Kota Tangerang</h5>
                    <h6>year 2016-2019</h6>
                    <h5>Universitas Indonesia</h5>
                    <h6>year 2019 till now</h6>
                </div>
                <img id="bulet2" src="{% static 'main/image/Bulet2.png' %}">
                <div class="experiences col">
                    <h4>Experiences</h4>
                    <h5>@ADStarShop owner</h5>
                    <h5>Member of School’s<br>Marching Band</h5>
                    <h5>Secretary of Raketnitra<br>Decoration Staff of Smanitra Cup<br>2017, 2019, and Nitrackers<br>Dropshipper (@cvonlinestore)</h5>
                    <h5>Academic Staff of BETIS<br>Media Staff of BEM Fasilkom UI</h5>
                </div>
            </div> 
            <img id="asetoval2" src="{% static 'main/image/AsetOval2.png' %}">    
            <img id="gelombang" src="{% static 'main/image/Gelombang2.png' %}" alt="asset">
        </div>
    </section>
    <section id="skills">
        <div class="col">
        <div class="kontenskills row">
            
            <div class="personalities col">
                <h4>PERSONALITIES</h4>
                <h5>Honesty</h5>
                <h5>Responsibilities</h5>
                <h5>Persistence</h5>
                <h5>Leadership</h5>
                <img id="param1" src="{% static 'main/image/Parameter1.png' %}" alt="param">
            </div>
            
            <div class="skills col">
                <h4>SKILLS</h4>
                <h5>Python, Java</h5>
                <h5>HTML, CSS</h5>
                <h5>Figma</h5>
                <h5>Photoshop</h5>
                <h5>Premiere Pro</h5>
                <h5>PicsArt wkwk</h5>
                <img id="param2" src="{% static 'main/image/Parameter2.png' %}" alt="param">
            </div>
            <img id="asetoval3" src="{% static 'main/image/AsetOval3.png' %}" alt="asset">
        </div>
        </div>
    </section>
    
    {% endblock content %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


    <!-- CSS EXTENDS -->
    {% block style %}
    {% endblock style %}

    <!-- {% block meta %}
    {% endblock meta %} -->
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand">
            <img id="logo" src="{% static 'main/image/logo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'main:profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'main:profile2' %}">Profile2</a>
                <a class="nav-item nav-link" href="{% url 'main:hobby' %}">Hobby</a>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <footer id="contactperson">
        <div class="footer col">
                <h7>Contact Person :</h7>
                <div class="sosmed row">
                    <a href="https://www.instagram.com/ichadevii/"> 
                        <img id="instagram" src="{% static 'main/image/Instagram.png' %}" alt="Instagram Saya">
                    </a> 
                    <a href="https://www.line.me/ichadevii/">
                        <img  id="line" src="{% static 'main/image/Line.png' %}" alt="Line Saya">
                    </a>
                    <a href="http://twitter.com/annisadevin/"> 
                        <img  id="twitter" src="{% static 'main/image/Twitter.png'%}" alt="Twitter Saya">
                    </a> 
                    <a href="adevi.nurmalasari@gmail.com">
                        <img  id="email" src="{% static 'main/image/Email.png' %}" alt="Email Saya">
                    </a>
                </div>
        </div>
    </footer>
</body>
  
</html>